### ISSUE TITLE
You know search sucks when...

### ISSUE THREAD

**Issue by olivierlacan** [orientation/orientation#114]
...this happens:
![image](https://cloud.githubusercontent.com/assets/65950/6862891/749a780c-d448-11e4-9900-e712a801da0f.png)

**Comment by olivierlacan** [comment]
I meant that no one noticed the duplicate when creating the article. Perhaps while typing an article title we should be checking for existing similar titles and if we get within `X` similarity, trigger a warning.

@drewbarontini @johndjameson Do you think a tooltip (on top of the title field) would be a good way to convey this unobtrusively?

There's also a question of whether to offer a link for the article drafter to check out the possible duplicate. Which in turn brings the issue of saving drafts in local storage (which we don't currently do) because if people accidentally visit another article while drafting, we may lose their draft and piss them off.

**Comment by drewbarontini** [comment]
We could also just trigger a notice on the page once they blur out of the title field.

**Comment by olivierlacan** [comment]
@drewbarontini Sounds good.

**Comment by bijanbwb** [comment]
I asked @snychka for a list of the main things that went well and what the major pain points were in terms of onboarding at Code School, and he mentioned how helpful Orientation has been... but that the search is limited and often makes it difficult to find existing articles.

I figured I'd post an example that I came across yesterday. I was looking for the article that contains information about filing a YouTube Copyright Complaint form, and I knew it existed because I [added a section to the bottom](http://orientation.codeschool.com/articles/filling-a-dmca-infringement#youtube). But it seems like it would be impossible to find without knowing the exact title of the Orientation article.

![hzdkkbfvgj](https://cloud.githubusercontent.com/assets/201320/7653237/2c81869e-fae2-11e4-9edf-bd7cb8060a7e.gif)

And here's an example where you would think that typing "Reset" would pull up articles about resetting courses or challenges or points, but it pulls up nothing at first:

![fzslzuzmgc](https://cloud.githubusercontent.com/assets/201320/7653290/94700f6e-fae2-11e4-8f47-750c8e13cf90.gif)

/cc @olivierlacan

**Comment by snychka** [comment]
Searching for two-factor authentication didn't work as well as hoped.  That
was the one example I remember.

I searched for *auth*, for example, but it only worked when I typed in the
first part of the title (it seems) *two-factor.*

Keep in mind, once you get used to things (so, pretty quickly), it's no
longer as big an issue.

Cheers

On Fri, May 15, 2015 at 6:14 AM, Bijan Boustani <notifications@github.com>
wrote:

> I asked @snychka <https://github.com/snychka> for a list of the main
> things that went well and what the major pain points were in terms of
> onboarding at Code School, and he mentioned how helpful Orientation has
> been... but that the search is limited and often makes it difficult to find
> existing articles.
>
> I figured I'd post an example that I came across yesterday. I was looking
> for the article that contains information about filing a YouTube Copyright
> Complaint form, and I knew it existed because I added a section to the
> bottom
> <http://orientation.codeschool.com/articles/filling-a-dmca-infringement#youtube>.
> But it seems like it would be impossible to find without knowing the exact
> title of the Orientation article.
>
> [image: hzdkkbfvgj]
> <https://cloud.githubusercontent.com/assets/201320/7653237/2c81869e-fae2-11e4-9edf-bd7cb8060a7e.gif>
>
> And here's an example where you would think that typing "Reset" would pull
> up articles about resetting courses or challenges or points, but it pulls
> up nothing at first:
>
> [image: fzslzuzmgc]
> <https://cloud.githubusercontent.com/assets/201320/7653290/94700f6e-fae2-11e4-8f47-750c8e13cf90.gif>
>
> /cc @olivierlacan <https://github.com/olivierlacan>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientation/orientation/issues/114#issuecomment-102393543>
> .
>



-- 
Stefan Nychka, stefannychka@gmail.com

**Comment by bijanbwb** [comment]
Here's another good example we can use to test out search after the updates:

![gydhpnhasv](https://cloud.githubusercontent.com/assets/201320/7728020/ab70697e-feda-11e4-93bf-e289ecc4ad27.gif)
