### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by ShadowBan** [orientation/orientation#116]
This seems like a great candidate to have an image up on [Docker Hub](https://registry.hub.docker.com).  I would love to just be able to boot the image and check it out!

**Comment by olivierlacan** [comment]
@ShadowBan I have no experience with Docker at all. Could you help me set this up?

**Comment by jefmathiot** [comment]
I don't know orientation but planned to give it a go using Docker. As Docker promotes one process per container, at least two images would be necessary, one to run the app, another one to run PostgreSQL, and probably an additional container to store the data (a data-volume container).

@ShadowBan what use case did ou have in mind? Be able to boot orientation in development? In this case docker-compose (formerly fig) could be a great candidate.

@olivierlacan @ShadowBan I'd be glad to lend a hand

**Comment by jefmathiot** [comment]
I'm working on the docker image right now. @olivierlacan what name / email adress should I use for the [MAINTAINER directive](https://docs.docker.com/reference/builder/#maintainer)?

**Comment by olivierlacan** [comment]
@jefmathiot 
> Olivier Lacan
> hi@olivierlacan.com

Thanks! :-)

**Comment by jefmathiot** [comment]
@olivierlacan almost done, I have a few questions:
* I'll need to document several use cases (using Postgres on the host, using a Postgres container, using compose). What do you think is the best location (wiki, Docker.md) ?
* We'll have to push the images on the Docker hub. Could you create an organization and add so that I can configure the build (jefmathiot)?
* I'll allow the user to specify an external .env file at runtime, are there other files I should be aware of (I create a specific database.yml file at build time)?

**Comment by ShadowBan** [comment]
@olivierlacan Yeah I was going to tackle this on monday as I was unfortunately busy this weekend... But it looks like @jefmathiot has got things under control.

@jefmathiot I was thinking of putting together a production container that could be linked to a postgres container and used for production deploys of that app.  I was also thinking of making a demo container that ran the app with a default .env and had postgres loaded in it.  The idea here is to be able to quickly check out the app in a local env without having to worry about dependencies and be able to easily clean up once done. 

@jefmathiot Please let me know if there is anything I can do to help!

**Comment by olivierlacan** [comment]
@jefmathiot `DOCKER.md`'s good. Invited you. Everything **should** be in `.env`. If it's not we should put it. :-)

@ShadowBan It's quite alright. I appreciate the initiative.

**Comment by olivierlacan** [comment]
@jefmathiot One important thing I forgot to mention in the README. CarrierWave depends on mini_magick which itself depends on imagemagick (for avatar image processing). I'm considering dropping this heavy dependency though and just rely on Gravatar for now. Do you think it'll add complexity to the Docker setup?

**Comment by jefmathiot** [comment]
@olivierlacan none of imagemagick / Gravatar add complexity. I've added imagemagick to the Dockerfile.

**Comment by jefmathiot** [comment]
@ShadowBan I gave you commit rights on [my fork](https://github.com/jefmathiot/orientation/tree/docker-build), so that we may improve the PR together :)

@olivierlacan I have not created the PR yet, because I'd like to document it properly and the "lack" of defaults make the onboarding experience a bit complicated (see below). I'm sure @ShadowBan will propose great improvements to this work in progress!

To use the image from the fork ("docker-build" branch), build it using "orientation" as the tag name:

```
docker build -t orientation .
```

Docker Compose is not mandatory at all, but to make the things work easier I've created the following `docker-compose.yml` file:

```
database:
  image: postgres
  command: postgres
  environment:
    POSTGRES_PASSWORD: "change-me!"
app:
  image: orientation
  ports:
    - "3000:3000"
  links:
    - database
  environment:
    DATABASE_NAME: "orientation"
    DATABASE_USERNAME: "postgres"
    DATABASE_PASSWORD: "change-me!"
    SECRET_KEY_BASE: "change-me!"
    SECRET_TOKEN: "change-me!"
```

Additional environment variables can be provided in the compose configuration.

Use `docker-compose up` to start the containers (`docker-compose stop && docker-compose rm --force` to destroy them). To create the database:

```
docker-compose run app rake db:create db:migrate
```
@olivierlacan in the `production` env, the app does not start if S3 credentials are not provided, so I've modified the initializer of CarrierWave to ensure it falls back to local storage, [see there](https://github.com/jefmathiot/orientation/commit/6a9192a7e869f7c5a8ef54ece0d39b13ae66f3b3).

That's not directly related to Docker, but the number of environment variables / dependencies to third-party services (with CarrierWave using file storaage by default, Google OAuth2, Mandrill remain on the list of prerequisites) introduces some friction IMHO.

**Comment by jefmathiot** [comment]
@olivierlacan forgot to ask: the Docker image is functional, do you think I should create the PR right now even if the documentation is missing?

**Comment by olivierlacan** [comment]
Yeah, you can open the PR and we'll work on it. Including what Jef brought up. John and I set him up yesterday and ran into those same issues. It's very likely I'm going to kill the CarrierWave avatar upload for now. I don't want people to have to setup an S3 bucket just to get Orientation running.

**Comment by jefmathiot** [comment]
@olivierlacan since I've merged with the master, the app doesn't boot anymore (in production) unless the `ORIENTATION_DOMAIN` env var is defined.

Maybe we could:
* expose the env vars to the app through a class or module providing consistent defaults when applicable?
* in the particular case of the `ORIENTATION_DOMAIN` variable, it is the hostname used in mailers, am I correct? Maybe in this specific case we could store get the host from the HTTP request, store it in the current thread so that the mailers can retrieve it? This way we could get rid of the env variable.

All of this is not directly related to Docker, but users of the Docker containers will expect the containers to run with almost zero configuration.
